// <auto-generated />
using DDocsBackend.Data.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DDocsBackend.Data.Cached
{
    [DbContext(typeof(DDocsContext))]
    public partial class DDocsContextModel : RuntimeModel
    {
        static DDocsContextModel()
        {
            var model = new DDocsContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DDocsContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
